# Register IP address
ip_address = aic_register

# port to register with register
register_port = 5558

# Node ID - must be unique (Amp1 = cell_id 3)
node_id = 3

# Port to publish measurements
pub_port = 5562
