# Node Messaging Broker Configuration
ip_address=0.0.0.0

# === DUMMY_NODE CHANNELS ===
# Measurement channel (dummy_node -> broker -> aic_app)
recv_measurements=5555
pub_measurements=5554

# Command channel (aic_app -> broker -> dummy_node)
recv_commands=5556
pub_commands=5557

# === OFC_NODE CHANNELS ===
# Measurement channel (ofc_node -> broker -> aic_ofc_app_2)
recv_ofc_measurements=5560
pub_ofc_measurements=5561

# === AMP1_NODE CHANNELS ===
# Measurement channel (ofc_amp1_node -> broker -> aic_ofc_app)
recv_amp1_measurements=5562
pub_amp1_commands=5563
