registration_ip_address = aic_register

# databus (node_msg_broker) ip address for measurements/commands
databus_ip_address = node_msg_broker

ip_address = 0.0.0.0

# port to listen for measurements coming from the BSs
recv_measurements = 5555

# port to publish the measuremetns (for the aic_apps)
pub_measurements = 5554

# port to listen for commands comming from the aic_apps
recv_commands = 5556

# port to publish the commands for the BS
pub_commands = 5557

## register sub
register_sub = 5558
