# Copyright (c) 2026 Trinity College Dublin
#
# This file is dual-licensed:
# - under the AGPL (see LICENSE)
# - under a commercial licence (contact infoknex@tcd.ie)

"""
AIC Application Base Class.

This module provides the base class for all AIC (AI Controller) applications
within the ai_nn_controller framework.
Control applications inherit from AicApp and implement their specific control
logic in the process() method.

The framework is domain-agnostic and supports any type of network node including
optical, wireless, RAN, core network, and more.

Example:
    .. code-block:: python

        from ai_nn_controller.AicApp import AicApp
        from ai_nn_controller.decorators.aic_app import aic_app

        @aic_app(name="MyControlApp")
        class MyControlApp(AicApp):
            aic_app_id = 1
            control_loop_update_time = 2
            read_measurements = {3: ["gain", "power"]}
            control_functions = {3: ["SET_GAIN"]}

            @classmethod
            def process(cls, measurements):
                # Control logic here
                pass

Note:
    cell_ids and send_commands are auto-generated by the @aic_app decorator
    and do not need to be defined in your application class.
"""

from .managers.AicManager import AicManager


class AicApp:
    """
    Base class for AIC control applications.

    This class provides the foundation for building control applications that
    manage any type of network node (optical, wireless, RAN, core, etc.).
    Subclasses should define their measurement subscriptions, control functions,
    and implement the process() method for custom control logic.

    Required Attributes (must be defined in your app):
        aic_app_id (int): Unique identifier for this application instance.
        control_loop_update_time (int): Interval in seconds between process() calls.
            Default is 1 second.
        read_measurements (dict): Dictionary mapping node IDs to lists of
            measurement names to subscribe to. Example: {3: ["gain", "power"]}
        control_functions (dict): Dictionary mapping node IDs to lists of
            command names available for that node. Example: {3: ["SET_GAIN"]}

    Auto-Generated Attributes (set by @aic_app decorator):
        send_commands (list): Queue of commands to be sent. Auto-initialized
            as empty list by the decorator.
        cell_ids (list): List of node IDs this application monitors.
            Auto-derived from read_measurements and control_functions keys.
        u_name (str): Unique name for the application, set by @aic_app decorator.
        agent_requests (list): Queue of AgentRequest objects from MCP agent-controlled
            tool calls. Drained by the controller after each process() cycle.
        _agent_handlers (dict): Map of operation name to handler callable,
            populated by @agent_controlled decorated methods.

    Note:
        Applications should be decorated with @aic_app(name="...") to be
        properly registered with the framework. Do not define cell_ids or
        send_commands in your app - they are auto-generated.
    """

    control_loop_update_time = 1
    read_measurements = {}
    control_functions = {}

    # Declare plugin dependencies by name.  The controller validates that every
    # listed plugin is registered at startup and injects live references into
    # cls.plugins before the first process() call.
    required_plugins: list = []

    # Populated by AicController.__aic_app_setup — do not set manually.
    plugins: dict = {}

    @classmethod
    def add_command(cls, command):
        """
        Add a command to the send queue.

        Commands added via this method will be processed and sent to the
        appropriate network nodes by the AicController.

        Args:
            command (tuple): A tuple containing:
                - command_name (str): Name of the registered command (e.g., "SET_GAIN")
                - payload (dict): Command parameters including:
                    - node_id (int): Target node ID
                    - value (dict): Command-specific parameters

        Example:
            .. code-block:: python

                cls.add_command((
                    "SET_GAIN",
                    {
                        "node_id": 8,
                        "value": {"amp_type": "preamp", "target_gain": 20.0}
                    }
                ))
        """
        cls.send_commands.append(command)

    @classmethod
    def process(cls, measurements):
        """
        Process incoming measurements and implement control logic.

        This method is called periodically by the AicController at intervals
        specified by time_interval. Subclasses should override this method
        to implement their specific control algorithms.

        Args:
            measurements (dict): Dictionary keyed by node_id (int), where each
                value is a list of measurement dictionaries received from that
                node since the last process() call.

                Example structure::

                    {
                        3: [{"gain": 20.5, "power": -10.2}, {"gain": 20.6, "power": -10.1}],
                        8: [{"preamp_gain": 15.0}]
                    }

        Note:
            - Use ``measurements.get(node_id, [])[-1]`` to get the latest
              measurement from a specific node.
            - Call ``cls.add_command()`` to queue commands for sending.
            - This method runs in a separate thread for each application.
        """
        pass
